services:
  postgres:
    image: postgres:18
    container_name: actions_postgres
    environment:
      POSTGRES_DB: actions_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
