services:
  # ============ KAFKA ============
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - MirrorBox

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - MirrorBox

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - MirrorBox

  # ============ ACTIONS SERVICE ============
  actions_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actions_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - MirrorBox
    depends_on:
      - actions_db
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=actions_db

  actions_http_server:
    image: nginx:alpine
    container_name: actions_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - MirrorBox
    depends_on:
      - actions_app

  actions_db:
    image: postgres:15-alpine
    container_name: actions_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: actions_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_actions:/var/lib/postgresql/data
    networks:
      - MirrorBox

  actions_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actions_consumer
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan kafka:consume
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC_REQUEST=client_to_actions
      - KAFKA_TOPIC_RESPONSE=actions_to_client
      - DB_HOST=actions_db
      - DB_PORT=5432
      - DB_DATABASE=actions_app
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
    networks:
      - MirrorBox
    depends_on:
      - kafka
      - actions_app
      - actions_db

networks:
  MirrorBox:
    driver: bridge

volumes:
  postgres_data_actions:
    driver: local
